namespace SignalsDotnet.SourceGenerators;

static class Attributes
{
    public const string GenerateSignalsAttributeName = "SignalsDotnet.GenerateSignalsAttribute";
    public const string SignalIgnoreAttributeName = "SignalsDotnet.SignalIgnoreAttribute";
    public const string SignalAttributeName = "SignalsDotnet.SignalAttribute";
    public const string ComputedAttributeName = "SignalsDotnet.ComputedAttribute";
    public const string AsyncComputedAttributeName = "SignalsDotnet.AsyncComputedAttribute";
    public const string GenerateNotifyPropertyChangedAttributeName = "SignalsDotnet.GenerateNotifyPropertyChangedAttribute";

    public const string Source = """
        // <auto-generated/>
        #nullable enable

        namespace SignalsDotnet
        {
            /// <summary>
            /// Marks a partial class whose partial auto properties should be backed by <see cref="Signal{T}"/> instances.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            internal sealed class GenerateSignalsAttribute : global::System.Attribute
            {
            }

            /// <summary>
            /// Makes the generated class implement <see cref="global::System.ComponentModel.INotifyPropertyChanged"/>
            /// and raise it whenever any generated property changes.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            internal sealed class GenerateNotifyPropertyChangedAttribute : global::System.Attribute
            {
                public GenerateNotifyPropertyChangedAttribute(bool enabled = true) => Enabled = enabled;

                /// <summary>
                /// When false no notification code is generated, as if the attribute were absent.
                /// </summary>
                public bool Enabled { get; }
            }

            /// <summary>
            /// Backs a single partial auto property with a <see cref="Signal{T}"/>, without needing
            /// <see cref="GenerateSignalsAttribute"/> on the declaring class.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            internal sealed class SignalAttribute : global::System.Attribute
            {
            }

            /// <summary>
            /// Excludes a property of a <see cref="GenerateSignalsAttribute"/> annotated class from signal generation.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            internal sealed class SignalIgnoreAttribute : global::System.Attribute
            {
            }

            /// <summary>
            /// Marks a parameterless method as the body of a computed signal. The generator emits a read only
            /// property named after the method, backed by a <see cref="global::SignalsDotnet.Signal"/>.Computed signal.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            internal sealed class ComputedAttribute : global::System.Attribute
            {
            }

            /// <summary>
            /// Marks a method taking a <see cref="global::System.Threading.CancellationToken"/> and returning a
            /// <see cref="global::System.Threading.Tasks.ValueTask{T}"/> or <see cref="global::System.Threading.Tasks.Task{T}"/>
            /// as the body of an asynchronous computed signal.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            internal sealed class AsyncComputedAttribute : global::System.Attribute
            {
                /// <summary>
                /// How a change arriving while a computation is still running is handled.
                /// </summary>
                public global::SignalsDotnet.ConcurrentChangeStrategy ConcurrentChangeStrategy { get; set; }
            }
        }
        """;
}
