using System.Text;

namespace SignalsDotnet.SourceGenerators;

static class Emitter
{
    const string SignalType = "global::SignalsDotnet.Signal";
    const string ReadOnlySignalType = "global::SignalsDotnet.IReadOnlySignal";
    const string NotifySignalChangedType = "global::SignalsDotnet.INotifySignalChanged";
    const string AsyncReadOnlySignalType = "global::SignalsDotnet.IAsyncReadOnlySignal";
    const string EffectType = "global::SignalsDotnet.Effect";

    public const string ModelChangedPropertyName = "ModelChanged";
    const string ModelChangedFieldName = "_modelChangedSignal";

    static void EmitIgnoreOnSerialization(IndentedBuilder builder, bool systemTextJsonAvailable)
    {
        builder.AppendLine("[global::System.Runtime.Serialization.IgnoreDataMember]");

        if (systemTextJsonAvailable)
            builder.AppendLine("[global::System.Text.Json.Serialization.JsonIgnore]");
    }

    public static string Emit(SignalClassModel model)
    {
        var builder = new IndentedBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (model.Namespace is not null)
        {
            builder.AppendLine($"namespace {model.Namespace}");
            builder.OpenBrace();
        }

        var hierarchy = model.Hierarchy.Items;
        for (var i = 0; i < hierarchy.Length; i++)
        {
            var declaration = hierarchy[i];
            var isTarget = i == hierarchy.Length - 1;
            var interfaces = isTarget
                             && model.NotifyPropertyChangedRequested
                             && !model.AlreadyImplementsINotifyPropertyChanged
                ? " : global::System.ComponentModel.INotifyPropertyChanged"
                : "";

            builder.AppendLine($"partial {declaration.Keyword} {declaration.Name}{interfaces}{declaration.Constraints}");
            builder.OpenBrace();
        }

        EmitBody(builder, model);

        for (var i = 0; i < hierarchy.Length; i++)
        {
            builder.CloseBrace();
        }

        if (model.Namespace is not null)
            builder.CloseBrace();

        return builder.ToString();
    }

    static void EmitBody(IndentedBuilder builder, SignalClassModel model)
    {
        var properties = model.Properties.Items;
        var notify = model.NotifyPropertyChangedRequested;
        var declareInpc = notify && !model.AlreadyImplementsINotifyPropertyChanged;

        for (var i = 0; i < properties.Length; i++)
        {
            if (i > 0)
                builder.AppendLine();

            EmitProperty(builder, properties[i], model.SystemTextJsonAvailable);
        }

        var computedProperties = model.ComputedProperties.Items;
        for (var i = 0; i < computedProperties.Length; i++)
        {
            if (i > 0 || properties.Length > 0)
                builder.AppendLine();

            EmitComputedProperty(builder, computedProperties[i], model.SystemTextJsonAvailable);
        }

        var asyncComputedProperties = model.AsyncComputedProperties.Items;
        for (var i = 0; i < asyncComputedProperties.Length; i++)
        {
            if (i > 0 || properties.Length > 0 || computedProperties.Length > 0)
                builder.AppendLine();

            EmitAsyncComputedProperty(builder, asyncComputedProperties[i], model.SystemTextJsonAvailable);
        }

        var effects = model.Effects.Items;
        for (var i = 0; i < effects.Length; i++)
        {
            if (i > 0 || properties.Length > 0 || computedProperties.Length > 0 || asyncComputedProperties.Length > 0)
                builder.AppendLine();

            EmitEffectField(builder, effects[i].FieldName, effects[i].MethodName);
        }

        var asyncEffects = model.AsyncEffects.Items;
        for (var i = 0; i < asyncEffects.Length; i++)
        {
            if (i > 0 || properties.Length > 0 || computedProperties.Length > 0 || asyncComputedProperties.Length > 0 || effects.Length > 0)
                builder.AppendLine();

            EmitEffectField(builder, asyncEffects[i].FieldName, asyncEffects[i].MethodName);
        }

        if (model.EmitModelChanged)
        {
            if (properties.Length > 0 || computedProperties.Length > 0 || asyncComputedProperties.Length > 0
                || effects.Length > 0 || asyncEffects.Length > 0)
            {
                builder.AppendLine();
            }

            EmitModelChanged(builder, properties, model.Hierarchy.Items[model.Hierarchy.Items.Length - 1].Name, model.SystemTextJsonAvailable);
        }

        var notified = notify
            ? properties.Select(static x => (x.Name, Source: x.FieldName))
                        .Concat(computedProperties.Select(static x => (x.Name, Source: x.FieldName)))
                        .Concat(asyncComputedProperties.Select(static x => (x.Name, Source: x.FieldName)))
                        .Concat(asyncComputedProperties.Select(static x => (Name: x.IsComputingPropertyName, Source: x.FieldName + ".IsComputing")))
                        .ToArray()
            : [];

        if (model.GenerateConstructor)
        {
            builder.AppendLine();
            builder.AppendLine($"public {model.ClassName}()");
            builder.OpenBrace();
            builder.AppendLine("InitializeSignals();");
            builder.CloseBrace();
        }

        builder.AppendLine();

        var initializedFields = properties.Select(static x => x.FieldName)
                                          .Concat(computedProperties.Select(static x => x.FieldName))
                                          .Concat(asyncComputedProperties.Select(static x => x.FieldName))
                                          .Concat(effects.Select(static x => x.FieldName))
                                          .Concat(asyncEffects.Select(static x => x.FieldName))
                                          .Concat(model.EmitModelChanged ? [ModelChangedFieldName] : Array.Empty<string>())
                                          .ToArray();

        if (initializedFields.Length > 0)
        {
            var names = string.Join(", ", initializedFields.Select(static x => $"nameof({x})"));
            builder.AppendLine($"[global::System.Diagnostics.CodeAnalysis.MemberNotNull({names})]");
        }

        var initializeSignalsAccessibility = model.IsStruct ? "private" : "protected";
        builder.AppendLine($"{initializeSignalsAccessibility} void InitializeSignals()");
        builder.OpenBrace();

        foreach (var property in properties)
        {
            var signalOfT = $"{SignalType}<{property.TypeName}>";
            builder.AppendLine($"{property.FieldName} = new {signalOfT}();");
        }

        if (properties.Length > 0 && (computedProperties.Length > 0 || asyncComputedProperties.Length > 0 || model.EmitModelChanged))
            builder.AppendLine();

        foreach (var computed in computedProperties)
        {
            builder.AppendLine($"{computed.FieldName} = {SignalType}.Computed({computed.MethodName});");
        }

        foreach (var computed in asyncComputedProperties)
        {
            var func = computed.ReturnsTask
                ? $"async (global::System.Threading.CancellationToken token) => await {computed.MethodName}(token)"
                : computed.MethodName;

            builder.AppendLine($"{computed.FieldName} = {SignalType}.AsyncComputed<{computed.TypeName}>({func}, default!, {computed.ConcurrentChangeStrategy});");
        }

        if (effects.Length > 0 || asyncEffects.Length > 0)
        {
            if (computedProperties.Length > 0 || asyncComputedProperties.Length > 0)
                builder.AppendLine();

            foreach (var effect in effects)
            {
                builder.AppendLine($"{effect.FieldName} = {EffectType}.Create({effect.MethodName});");
            }

            foreach (var effect in asyncEffects)
            {
                var func = effect.ReturnsTask
                    ? $"async (global::System.Threading.CancellationToken token) => await {effect.MethodName}(token)"
                    : effect.MethodName;

                builder.AppendLine($"{effect.FieldName} = {EffectType}.Create({func}, {effect.ConcurrentChangeStrategy});");
            }
        }

        if (model.EmitModelChanged)
        {
            if (computedProperties.Length > 0 || asyncComputedProperties.Length > 0 || effects.Length > 0 || asyncEffects.Length > 0)
                builder.AppendLine();

            var modelTypeName = model.Hierarchy.Items[model.Hierarchy.Items.Length - 1].Name;

            builder.AppendLine($"{ModelChangedFieldName} = {SignalType}.Computed<{modelTypeName}>(() =>");
            builder.OpenBrace();

            foreach (var property in properties)
            {
                builder.AppendLine($"_ = {property.FieldName}.Value;");
            }

            builder.AppendLine("return this;");
            builder.CloseBrace(", config => config with { RaiseOnlyWhenChanged = false });");
        }

        if (notified.Length > 0
            && (computedProperties.Length > 0 || asyncComputedProperties.Length > 0
                || effects.Length > 0 || asyncEffects.Length > 0 || model.EmitModelChanged))
        {
            builder.AppendLine();
        }

        foreach (var (name, field) in notified)
        {
            builder.AppendLine($"global::R3.ObservableSubscribeExtensions.Subscribe((({NotifySignalChangedType}){field}).FutureValuesUntracked, _ => OnPropertyChanged(nameof({name})));");
        }

        builder.CloseBrace();

        if (model.IsRecord)
            EmitRecordMembers(builder, model, properties);

        if (declareInpc)
        {
            builder.AppendLine();
            builder.AppendLine("/// <inheritdoc />");
            builder.AppendLine("public event global::System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;");
            builder.AppendLine();
            builder.AppendLine("protected virtual void OnPropertyChanged(string propertyName)");
            builder.OpenBrace();
            builder.AppendLine("PropertyChanged?.Invoke(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName));");
            builder.CloseBrace();
        }
    }

    static void EmitRecordMembers(IndentedBuilder builder, SignalClassModel model, SignalPropertyModel[] dataProperties)
    {
        var typeName = model.Hierarchy.Items[model.Hierarchy.Items.Length - 1].Name;

        if (!model.IsRecordStruct)
        {
            builder.AppendLine();
            builder.AppendLine("/// <summary>Copy constructor giving the clone its own signals, so 'with' does not alias the original.</summary>");
            builder.AppendLine($"{(model.IsSealed ? "private" : "protected")} {model.ClassName}({typeName} original)");
            builder.OpenBrace();
            builder.AppendLine("if (original is null) throw new global::System.ArgumentNullException(nameof(original));");
            builder.AppendLine("InitializeSignals();");

            foreach (var property in dataProperties)
            {
                builder.AppendLine($"{property.FieldName}.Value = original.{property.Name};");
            }

            builder.CloseBrace();
        }

        builder.AppendLine();
        builder.AppendLine("/// <summary>Prints only the signal backed data properties, hiding the generated signals.</summary>");

        var printModifiers = model.IsRecordStruct || model.IsSealed ? "private" : "protected virtual";

        builder.AppendLine($"{printModifiers} bool PrintMembers(global::System.Text.StringBuilder builder)");
        builder.OpenBrace();

        if (dataProperties.Length == 0)
        {
            builder.AppendLine("return false;");
        }
        else
        {
            for (var i = 0; i < dataProperties.Length; i++)
            {
                if (i > 0)
                    builder.AppendLine("builder.Append(\", \");");

                builder.AppendLine($"builder.Append(\"{dataProperties[i].Name} = \").Append((object?){dataProperties[i].Name});");
            }

            builder.AppendLine("return true;");
        }

        builder.CloseBrace();

        builder.AppendLine();
        builder.AppendLine("/// <summary>Compares only the signal backed data properties.</summary>");

        var equalsModifier = model.IsRecordStruct ? "public" : "public virtual";
        var nullableSuffix = model.IsRecordStruct ? "" : "?";

        builder.AppendLine($"{equalsModifier} bool Equals({typeName}{nullableSuffix} other)");
        builder.OpenBrace();

        if (!model.IsRecordStruct)
        {
            builder.AppendLine("if (other is null) return false;");
            builder.AppendLine("if (global::System.Object.ReferenceEquals(this, other)) return true;");
            builder.AppendLine("if (EqualityContract != other.EqualityContract) return false;");
        }

        if (dataProperties.Length == 0)
        {
            builder.AppendLine("return true;");
        }
        else
        {
            for (var i = 0; i < dataProperties.Length; i++)
            {
                var property = dataProperties[i];
                var prefix = i == 0 ? "return " : "       && ";
                var suffix = i == dataProperties.Length - 1 ? ";" : "";

                builder.AppendLine($"{prefix}global::System.Collections.Generic.EqualityComparer<{property.TypeName}>.Default.Equals({property.Name}, other.{property.Name}){suffix}");
            }
        }

        builder.CloseBrace();

        builder.AppendLine();
        builder.AppendLine("/// <inheritdoc />");
        builder.AppendLine("public override int GetHashCode()");
        builder.OpenBrace();

        if (dataProperties.Length == 0)
        {
            builder.AppendLine("return 0;");
        }
        else
        {
            builder.AppendLine("var hash = new global::System.HashCode();");

            if (!model.IsRecordStruct)
                builder.AppendLine("hash.Add(EqualityContract);");

            foreach (var property in dataProperties)
            {
                builder.AppendLine($"hash.Add({property.Name});");
            }

            builder.AppendLine("return hash.ToHashCode();");
        }

        builder.CloseBrace();
    }

    static void EmitModelChanged(IndentedBuilder builder, SignalPropertyModel[] properties, string typeName, bool systemTextJsonAvailable)
    {
        var signalOfModel = $"{ReadOnlySignalType}<{typeName}>";

        builder.AppendLine($"private {signalOfModel} {ModelChangedFieldName} = null!;");
        builder.AppendLine();

        builder.AppendLine("/// <summary>");
        builder.AppendLine($"/// Signal holding this instance, raised whenever any of {DescribeProperties(properties)} changes.");
        builder.AppendLine("/// </summary>");
        EmitIgnoreOnSerialization(builder, systemTextJsonAvailable);
        builder.AppendLine($"public {signalOfModel} {ModelChangedPropertyName} => {ModelChangedFieldName};");
    }

    static string DescribeProperties(SignalPropertyModel[] properties)
    {
        var names = properties.Select(static x => $"<see cref=\"{x.Name}\"/>").ToArray();
        if (names.Length == 1)
            return names[0];

        var head = string.Join(", ", names.Take(names.Length - 1));
        return $"{head} or {names[names.Length - 1]}";
    }

    static void EmitProperty(IndentedBuilder builder, SignalPropertyModel property, bool systemTextJsonAvailable)
    {
        var signalOfT = $"{SignalType}<{property.TypeName}>";

        builder.AppendLine($"private {signalOfT} {property.FieldName} = null!;");
        builder.AppendLine();

        builder.AppendLine($"/// <summary>Signal backing <see cref=\"{property.Name}\"/>.</summary>");
        EmitIgnoreOnSerialization(builder, systemTextJsonAvailable);
        builder.AppendLine($"{property.Accessibility} {ReadOnlySignalType}<{property.TypeName}> {property.SignalPropertyName} => {property.FieldName};");
        builder.AppendLine();

        builder.AppendLine($"/// <inheritdoc cref=\"{property.Name}\"/>");
        builder.AppendLine($"{property.Accessibility} partial {property.TypeName} {property.Name}");
        builder.OpenBrace();
        builder.AppendLine($"get => {property.FieldName}.Value;");

        if (property.HasSetter)
        {
            var setterKeyword = property.IsInitOnly ? "init" : "set";
            var accessibility = property.SetterAccessibility is null ? "" : property.SetterAccessibility + " ";

            builder.AppendLine($"{accessibility}{setterKeyword} => {property.FieldName}.Value = value;");
        }

        builder.CloseBrace();
    }

    static void EmitAsyncComputedProperty(IndentedBuilder builder, AsyncComputedPropertyModel property, bool systemTextJsonAvailable)
    {
        var asyncSignalOfT = $"{AsyncReadOnlySignalType}<{property.TypeName}>";

        builder.AppendLine($"private {asyncSignalOfT} {property.FieldName} = null!;");
        builder.AppendLine();

        builder.AppendLine($"/// <summary>Asynchronous computed signal backing <see cref=\"{property.Name}\"/>.</summary>");
        EmitIgnoreOnSerialization(builder, systemTextJsonAvailable);
        builder.AppendLine($"{property.Accessibility} {asyncSignalOfT} {property.SignalPropertyName} => {property.FieldName};");
        builder.AppendLine();

        builder.AppendLine($"/// <summary>True while <see cref=\"{property.MethodName}\"/> is running.</summary>");
        EmitIgnoreOnSerialization(builder, systemTextJsonAvailable);
        builder.AppendLine($"{property.Accessibility} bool {property.IsComputingPropertyName} => {property.FieldName}.IsComputing.Value;");
        builder.AppendLine();

        builder.AppendLine($"/// <summary>Computed from <see cref=\"{property.MethodName}\"/>.</summary>");
        EmitIgnoreOnSerialization(builder, systemTextJsonAvailable);
        builder.AppendLine($"{property.Accessibility} {property.TypeName} {property.Name} => {property.FieldName}.Value;");
    }

    static void EmitEffectField(IndentedBuilder builder, string fieldName, string methodName)
    {
        builder.AppendLine($"/// <summary>Keeps <see cref=\"{methodName}\"/> running as an effect for the lifetime of this instance.</summary>");
        builder.AppendLine($"private {EffectType} {fieldName} = null!;");
    }

    static void EmitComputedProperty(IndentedBuilder builder, ComputedPropertyModel property, bool systemTextJsonAvailable)
    {
        var readOnlySignalOfT = $"{ReadOnlySignalType}<{property.TypeName}>";

        builder.AppendLine($"private {readOnlySignalOfT} {property.FieldName} = null!;");
        builder.AppendLine();

        builder.AppendLine($"/// <summary>Computed signal backing <see cref=\"{property.Name}\"/>.</summary>");
        EmitIgnoreOnSerialization(builder, systemTextJsonAvailable);
        builder.AppendLine($"{property.Accessibility} {readOnlySignalOfT} {property.SignalPropertyName} => {property.FieldName};");
        builder.AppendLine();

        builder.AppendLine($"/// <summary>Computed from <see cref=\"{property.MethodName}\"/>.</summary>");
        EmitIgnoreOnSerialization(builder, systemTextJsonAvailable);
        builder.AppendLine($"{property.Accessibility} {property.TypeName} {property.Name} => {property.FieldName}.Value;");
    }
}

sealed class IndentedBuilder
{
    readonly StringBuilder _builder = new();
    int _indent;

    public void AppendLine()
    {
        _builder.AppendLine();
    }

    public void AppendLine(string line)
    {
        _builder.Append(' ', _indent * 4);
        _builder.AppendLine(line);
    }

    public void OpenBrace()
    {
        AppendLine("{");
        _indent++;
    }

    public void CloseBrace()
    {
        _indent--;
        AppendLine("}");
    }

    public void CloseBrace(string suffix)
    {
        _indent--;
        AppendLine("}" + suffix);
    }

    public override string ToString() => _builder.ToString();
}
