using System.Text;

namespace SignalsDotnet.SourceGenerators;

static class Emitter
{
    const string SignalType = "global::SignalsDotnet.Signal";
    const string ReadOnlySignalType = "global::SignalsDotnet.IReadOnlySignal";
    const string NotifySignalChangedType = "global::SignalsDotnet.INotifySignalChanged";
    const string AsyncReadOnlySignalType = "global::SignalsDotnet.IAsyncReadOnlySignal";

    public static string Emit(SignalClassModel model)
    {
        var builder = new IndentedBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (model.Namespace is not null)
        {
            builder.AppendLine($"namespace {model.Namespace}");
            builder.OpenBrace();
        }

        var hierarchy = model.Hierarchy.Items;
        for (var i = 0; i < hierarchy.Length; i++)
        {
            var declaration = hierarchy[i];
            var isTarget = i == hierarchy.Length - 1;
            var interfaces = isTarget
                             && model.NotifyPropertyChangedRequested
                             && !model.AlreadyImplementsINotifyPropertyChanged
                ? " : global::System.ComponentModel.INotifyPropertyChanged"
                : "";

            builder.AppendLine($"partial {declaration.Keyword} {declaration.Name}{interfaces}{declaration.Constraints}");
            builder.OpenBrace();
        }

        EmitBody(builder, model);

        for (var i = 0; i < hierarchy.Length; i++)
        {
            builder.CloseBrace();
        }

        if (model.Namespace is not null)
            builder.CloseBrace();

        return builder.ToString();
    }

    static void EmitBody(IndentedBuilder builder, SignalClassModel model)
    {
        var properties = model.Properties.Items;
        var notify = model.NotifyPropertyChangedRequested;
        var declareInpc = notify && !model.AlreadyImplementsINotifyPropertyChanged;

        for (var i = 0; i < properties.Length; i++)
        {
            if (i > 0)
                builder.AppendLine();

            EmitProperty(builder, properties[i]);
        }

        var computedProperties = model.ComputedProperties.Items;
        for (var i = 0; i < computedProperties.Length; i++)
        {
            if (i > 0 || properties.Length > 0)
                builder.AppendLine();

            EmitComputedProperty(builder, computedProperties[i]);
        }

        var asyncComputedProperties = model.AsyncComputedProperties.Items;
        for (var i = 0; i < asyncComputedProperties.Length; i++)
        {
            if (i > 0 || properties.Length > 0 || computedProperties.Length > 0)
                builder.AppendLine();

            EmitAsyncComputedProperty(builder, asyncComputedProperties[i]);
        }

        var notified = notify
            ? properties.Select(static x => (x.Name, Source: x.FieldName))
                        .Concat(computedProperties.Select(static x => (x.Name, Source: x.FieldName)))
                        .Concat(asyncComputedProperties.Select(static x => (x.Name, Source: x.FieldName)))
                        .Concat(asyncComputedProperties.Select(static x => (Name: x.IsComputingPropertyName, Source: x.FieldName + ".IsComputing")))
                        .ToArray()
            : [];

        builder.AppendLine();
        builder.AppendLine($"public {model.ClassName}()");
        builder.OpenBrace();

        foreach (var computed in computedProperties)
        {
            builder.AppendLine($"{computed.FieldName} = {SignalType}.Computed({computed.MethodName});");
        }

        foreach (var computed in asyncComputedProperties)
        {
            var func = computed.ReturnsTask
                ? $"async (global::System.Threading.CancellationToken token) => await {computed.MethodName}(token)"
                : computed.MethodName;

            builder.AppendLine($"{computed.FieldName} = {SignalType}.AsyncComputed<{computed.TypeName}>({func}, default!, {computed.ConcurrentChangeStrategy});");
        }

        if (notified.Length > 0 && (computedProperties.Length > 0 || asyncComputedProperties.Length > 0))
            builder.AppendLine();

        foreach (var (name, field) in notified)
        {
            builder.AppendLine($"global::R3.ObservableSubscribeExtensions.Subscribe((({NotifySignalChangedType}){field}).FutureValuesUntracked, _ => OnPropertyChanged(nameof({name})));");
        }

        builder.AppendLine();
        builder.AppendLine("OnInitialized();");
        builder.CloseBrace();
        builder.AppendLine();

        builder.AppendLine("/// <summary>Called once the generated signals are initialized. Implement it to run your own construction logic.</summary>");
        builder.AppendLine("partial void OnInitialized();");

        if (declareInpc)
        {
            builder.AppendLine();
            builder.AppendLine("/// <inheritdoc />");
            builder.AppendLine("public event global::System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;");
            builder.AppendLine();
            builder.AppendLine("protected virtual void OnPropertyChanged(string propertyName)");
            builder.OpenBrace();
            builder.AppendLine("PropertyChanged?.Invoke(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName));");
            builder.CloseBrace();
        }
    }

    static void EmitProperty(IndentedBuilder builder, SignalPropertyModel property)
    {
        var signalOfT = $"{SignalType}<{property.TypeName}>";

        builder.AppendLine($"private readonly {signalOfT} {property.FieldName} = new {signalOfT}();");
        builder.AppendLine();

        builder.AppendLine($"/// <summary>Signal backing <see cref=\"{property.Name}\"/>.</summary>");
        builder.AppendLine($"{property.Accessibility} {ReadOnlySignalType}<{property.TypeName}> {property.SignalPropertyName} => {property.FieldName};");
        builder.AppendLine();

        builder.AppendLine($"/// <inheritdoc cref=\"{property.Name}\"/>");
        builder.AppendLine($"{property.Accessibility} partial {property.TypeName} {property.Name}");
        builder.OpenBrace();
        builder.AppendLine($"get => {property.FieldName}.Value;");

        if (property.HasSetter)
        {
            var setterKeyword = property.IsInitOnly ? "init" : "set";
            var accessibility = property.SetterAccessibility is null ? "" : property.SetterAccessibility + " ";

            builder.AppendLine($"{accessibility}{setterKeyword} => {property.FieldName}.Value = value;");
        }

        builder.CloseBrace();
    }

    static void EmitAsyncComputedProperty(IndentedBuilder builder, AsyncComputedPropertyModel property)
    {
        var asyncSignalOfT = $"{AsyncReadOnlySignalType}<{property.TypeName}>";

        builder.AppendLine($"private readonly {asyncSignalOfT} {property.FieldName};");
        builder.AppendLine();

        builder.AppendLine($"/// <summary>Asynchronous computed signal backing <see cref=\"{property.Name}\"/>.</summary>");
        builder.AppendLine($"{property.Accessibility} {asyncSignalOfT} {property.SignalPropertyName} => {property.FieldName};");
        builder.AppendLine();

        builder.AppendLine($"/// <summary>True while <see cref=\"{property.MethodName}\"/> is running.</summary>");
        builder.AppendLine($"{property.Accessibility} bool {property.IsComputingPropertyName} => {property.FieldName}.IsComputing.Value;");
        builder.AppendLine();

        builder.AppendLine($"/// <summary>Computed from <see cref=\"{property.MethodName}\"/>.</summary>");
        builder.AppendLine($"{property.Accessibility} {property.TypeName} {property.Name} => {property.FieldName}.Value;");
    }

    static void EmitComputedProperty(IndentedBuilder builder, ComputedPropertyModel property)
    {
        var readOnlySignalOfT = $"{ReadOnlySignalType}<{property.TypeName}>";

        builder.AppendLine($"private readonly {readOnlySignalOfT} {property.FieldName};");
        builder.AppendLine();

        builder.AppendLine($"/// <summary>Computed signal backing <see cref=\"{property.Name}\"/>.</summary>");
        builder.AppendLine($"{property.Accessibility} {readOnlySignalOfT} {property.SignalPropertyName} => {property.FieldName};");
        builder.AppendLine();

        builder.AppendLine($"/// <summary>Computed from <see cref=\"{property.MethodName}\"/>.</summary>");
        builder.AppendLine($"{property.Accessibility} {property.TypeName} {property.Name} => {property.FieldName}.Value;");
    }
}

sealed class IndentedBuilder
{
    readonly StringBuilder _builder = new();
    int _indent;

    public void AppendLine()
    {
        _builder.AppendLine();
    }

    public void AppendLine(string line)
    {
        _builder.Append(' ', _indent * 4);
        _builder.AppendLine(line);
    }

    public void OpenBrace()
    {
        AppendLine("{");
        _indent++;
    }

    public void CloseBrace()
    {
        _indent--;
        AppendLine("}");
    }

    public void CloseBrace(string suffix)
    {
        _indent--;
        AppendLine("}" + suffix);
    }

    public override string ToString() => _builder.ToString();
}
