<Project Sdk="Microsoft.NET.Sdk">

		<PropertyGroup>
				<TargetFrameworks>net8.0;netstandard2.1</TargetFrameworks>
				<ImplicitUsings>enable</ImplicitUsings>
				<Nullable>enable</Nullable>
				<Description>Redis backed signals store for SignalsDotnet</Description>
				<RepositoryUrl>https://github.com/fedeAlterio/SignalsDotnet</RepositoryUrl>
				<Version>2.3.1</Version>
				<langversion>latest</langversion>
				<PackageProjectUrl>https://github.com/fedeAlterio/SignalsDotnet</PackageProjectUrl>
		</PropertyGroup>

		<ItemGroup>
				<ProjectReference Include="..\SignalsDotnet.SignalsStore\SignalsDotnet.SignalsStore.csproj" />

				<PackageReference Include="PolySharp" Version="1.14.1">
						<PrivateAssets>all</PrivateAssets>
						<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
				</PackageReference>

				<PackageReference Include="StackExchange.Redis" Version="2.8.24" />
		</ItemGroup>

		<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
				<PackageReference Include="System.Text.Json" Version="8.0.5" />
		</ItemGroup>

</Project>
